name: supabase_edge_functions_example
description: A Supaabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: 0.0.7
  edge_http_client: 0.0.1+3
  supabase: 1.11.9
  supabase_functions: 0.0.2+4

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  realtime_client: 1.2.3
