name: Flutter CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./supabase-ws-flutter-mobile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: dart-lang/setup-dart@v1.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Cache FVM & Flutter
        uses: actions/cache@v3
        with:
          path: /home/runner/fvm/versions/
          key: ${{ runner.os }}-${{ hashFiles('**/fvm_config.json') }}
      - name: Cache pub cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.pub-cache/
          key: ${{ runner.os }}-pub-cache
      - name: Install FVM && Flutter
        run: dart pub global activate fvm --verbose && fvm install --verbose && fvm use --force --verbose
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./supabase-ws-flutter-mobile
      - name: Activate arb_utils
        run: |
          dart pub global activate arb_utils
      - name: Get dependencies
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'fetch_dependencies'
          subdirectory: 'supabase-ws-flutter-mobile'
      - name: 'Run lints'
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'lints'
          subdirectory: 'supabase-ws-flutter-mobile'
      - name: 'Check generated code'
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'ensure_no_change_in_generated_code'
          subdirectory: 'supabase-ws-flutter-mobile'
      - name: 'Run tests'
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'tests'
          subdirectory: 'supabase-ws-flutter-mobile'
      - name: 'Build android app'
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'android build_dev_debug_apk'
          subdirectory: 'supabase-ws-flutter-mobile/android'
